import { type User, type InsertUser, type Transaction, type InsertTransaction, type Card, type InsertCard, type CryptoAsset, type InsertCryptoAsset } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  getUser(id: string): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
  getUserTransactions(userId: string): Promise<Transaction[]>;
  createTransaction(transaction: InsertTransaction): Promise<Transaction>;
  getUserCards(userId: string): Promise<Card[]>;
  createCard(card: InsertCard): Promise<Card>;
  getCryptoAssets(): Promise<CryptoAsset[]>;
  updateCryptoAsset(asset: CryptoAsset): Promise<CryptoAsset>;
}

export class MemStorage implements IStorage {
  private users: Map<string, User>;
  private transactions: Map<string, Transaction>;
  private cards: Map<string, Card>;
  private cryptoAssets: Map<string, CryptoAsset>;

  constructor() {
    this.users = new Map();
    this.transactions = new Map();
    this.cards = new Map();
    this.cryptoAssets = new Map();
    this.seedData();
  }

  private seedData() {
    // Create Thomas Francis user
    const thomasId = randomUUID();
    const thomas: User = {
      id: thomasId,
      username: "thomas.francis",
      firstName: "Thomas",
      lastName: "Francis",
      email: "thomas@example.com",
      avatar: "TF",
      balance: "2.19",
      currency: "AUD",
      plan: "Personal",
      createdAt: new Date(),
    };
    this.users.set(thomasId, thomas);

    // Create cards
    const originalCard: Card = {
      id: randomUUID(),
      userId: thomasId,
      type: "original",
      name: "Original",
      lastFour: "1234",
      isActive: true,
      description: "Fully activate card",
      createdAt: new Date(),
    };

    const disposableCard: Card = {
      id: randomUUID(),
      userId: thomasId,
      type: "disposable",
      name: "Disposable",
      lastFour: "5678",
      isActive: true,
      description: "Regenerates details after each use",
      createdAt: new Date(),
    };

    this.cards.set(originalCard.id, originalCard);
    this.cards.set(disposableCard.id, disposableCard);

    // Create transactions - European Trip 2025 + existing transactions
    const transactions: Omit<Transaction, 'id'>[] = [
      // European Trip Transactions - June/July 2025
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "10000.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Top Up",
        status: "completed",
        description: "09:12",
        date: new Date("2025-06-25T09:12:00"),
        merchantIcon: "apple",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Gail's Bakery Mayfair",
        amount: "-9.80",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "08:07 • -A$18.13",
        date: new Date("2025-06-27T08:07:00"),
        merchantIcon: "G",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Hard Rock Cafe London - Old Park Lane",
        amount: "-28.50",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "12:46 • -A$52.73",
        date: new Date("2025-06-27T12:46:00"),
        merchantIcon: "H",
        iconColor: "#EC4899",
      },
      {
        userId: thomasId,
        merchant: "Transport for London",
        amount: "-2.60",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Transport",
        status: "completed",
        description: "15:31 • -A$4.81",
        date: new Date("2025-06-27T15:31:00"),
        merchantIcon: "TFL",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Starbucks Oxford Street 75",
        amount: "-3.30",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "16:04 • -A$6.11",
        date: new Date("2025-06-27T16:04:00"),
        merchantIcon: "S",
        iconColor: "#00704A",
      },
      {
        userId: thomasId,
        merchant: "Dishoom Carnaby",
        amount: "-62.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "19:47 • -A$114.70",
        date: new Date("2025-06-27T19:47:00"),
        merchantIcon: "D",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Ronnie Scott's Jazz Club",
        amount: "-30.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Entertainment",
        status: "completed",
        description: "22:03 • -A$55.50",
        date: new Date("2025-06-27T22:03:00"),
        merchantIcon: "R",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "The Wolseley",
        amount: "-110.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "10:16 • -A$203.50",
        date: new Date("2025-06-28T10:16:00"),
        merchantIcon: "W",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Harrods",
        amount: "-680.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Shopping",
        status: "completed",
        description: "13:42 • -A$1,258.00",
        date: new Date("2025-06-28T13:42:00"),
        merchantIcon: "H",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Dinner by Heston Blumenthal",
        amount: "-432.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "20:19 • -A$799.20",
        date: new Date("2025-06-28T20:19:00"),
        merchantIcon: "D",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Notes Coffee Roasters & Bar",
        amount: "-9.00",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "09:04 • -A$16.65",
        date: new Date("2025-06-29T09:04:00"),
        merchantIcon: "N",
        iconColor: "#8B4513",
      },
      {
        userId: thomasId,
        merchant: "Pret A Manger Strand",
        amount: "-3.80",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Food & Drink",
        status: "completed",
        description: "09:17 • -A$7.03",
        date: new Date("2025-06-29T09:17:00"),
        merchantIcon: "P",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "British Museum Ticket Office",
        amount: "-30.00",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "11:54 • -A$55.50",
        date: new Date("2025-06-29T11:54:00"),
        merchantIcon: "B",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "British Museum Gift Shop",
        amount: "-15.00",
        currency: "AUD",
        category: "Shopping",
        status: "completed",
        description: "13:22 • -A$27.75",
        date: new Date("2025-06-29T13:22:00"),
        merchantIcon: "B",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "The Montague on The Gardens",
        amount: "-86.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "14:49 • -A$159.10",
        date: new Date("2025-06-29T14:49:00"),
        merchantIcon: "M",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Sherlock: The Official Live Game",
        amount: "-198.00",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "21:30 • -A$366.30",
        date: new Date("2025-06-29T21:30:00"),
        merchantIcon: "S",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Premiere Cinemas Romford",
        amount: "-25.60",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "09:02 • -A$47.36",
        date: new Date("2025-06-30T09:02:00"),
        merchantIcon: "P",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Taxis Combined Dublin",
        amount: "-48.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "12:52 • -A$79.20",
        date: new Date("2025-06-30T12:52:00"),
        merchantIcon: "T",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "The Temple Bar Pub",
        amount: "-18.70",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "20:47 • -A$30.86",
        date: new Date("2025-06-30T20:47:00"),
        merchantIcon: "T",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "The Stag's Head",
        amount: "-22.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "11:58 • -A$36.30",
        date: new Date("2025-07-01T11:58:00"),
        merchantIcon: "S",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "The Brazen Head",
        amount: "-16.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "21:36 • -A$26.40",
        date: new Date("2025-07-01T21:36:00"),
        merchantIcon: "B",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Butlers Chocolate Café - Grafton St",
        amount: "-8.50",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "10:09 • -A$14.03",
        date: new Date("2025-07-02T10:09:00"),
        merchantIcon: "B",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Guinness Storehouse Tickets",
        amount: "-52.00",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "13:02 • -A$85.80",
        date: new Date("2025-07-02T13:02:00"),
        merchantIcon: "G",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Gravity Bar - Guinness",
        amount: "-17.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "14:51 • -A$28.05",
        date: new Date("2025-07-02T14:51:00"),
        merchantIcon: "G",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "The Church Café Bar",
        amount: "-44.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "19:46 • -A$72.60",
        date: new Date("2025-07-02T19:46:00"),
        merchantIcon: "C",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Grogan's Castle Lounge",
        amount: "-24.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "15:41 • -A$39.60",
        date: new Date("2025-07-03T15:41:00"),
        merchantIcon: "G",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "O'Donoghue's",
        amount: "-26.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "22:14 • -A$42.90",
        date: new Date("2025-07-03T22:14:00"),
        merchantIcon: "O",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Circle K Athlone",
        amount: "-36.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "09:03 • -A$59.40",
        date: new Date("2025-07-04T09:03:00"),
        merchantIcon: "C",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Kylemore Abbey & Gardens",
        amount: "-30.00",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "12:21 • -A$49.50",
        date: new Date("2025-07-04T12:21:00"),
        merchantIcon: "K",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Kylemore Café",
        amount: "-22.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "13:17 • -A$36.30",
        date: new Date("2025-07-04T13:17:00"),
        merchantIcon: "K",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Lowry's Bar Clifden",
        amount: "-28.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "16:02 • -A$46.20",
        date: new Date("2025-07-04T16:02:00"),
        merchantIcon: "L",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Heuston Station - Coffee Dock",
        amount: "-4.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "07:48 • -A$6.60",
        date: new Date("2025-07-05T07:48:00"),
        merchantIcon: "H",
        iconColor: "#8B4513",
      },
      {
        userId: thomasId,
        merchant: "Heathrow Express",
        amount: "-37.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "09:10 • -A$61.05",
        date: new Date("2025-07-05T09:10:00"),
        merchantIcon: "H",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Addison Lee",
        amount: "-65.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "11:46 • -A$120.25",
        date: new Date("2025-07-05T11:46:00"),
        merchantIcon: "A",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Caffè Nero - Heathrow T5A",
        amount: "-7.40",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "12:27 • -A$13.69",
        date: new Date("2025-07-05T12:27:00"),
        merchantIcon: "C",
        iconColor: "#8B4513",
      },
      {
        userId: thomasId,
        merchant: "British Airways",
        amount: "-145.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "13:55 • -A$239.25",
        date: new Date("2025-07-05T13:55:00"),
        merchantIcon: "BA",
        iconColor: "#0066CC",
      },
      // Italian segment of the trip
      {
        userId: thomasId,
        merchant: "Taxi Roma NCC",
        amount: "-52.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "15:26 • -A$85.80",
        date: new Date("2025-07-14T15:26:00"),
        merchantIcon: "T",
        iconColor: "#0066CC",
      },
      {
        userId: thomasId,
        merchant: "Hotel Eden Roma",
        amount: "-900.00",
        currency: "AUD",
        category: "Accommodation",
        status: "completed",
        description: "16:18 • -A$1,485.00",
        date: new Date("2025-07-14T16:18:00"),
        merchantIcon: "H",
        iconColor: "#A855F7",
      },
      {
        userId: thomasId,
        merchant: "Ristorante Il Chianti Roma",
        amount: "-210.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "19:51 • -A$346.50",
        date: new Date("2025-07-14T19:51:00"),
        merchantIcon: "R",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "10000.00",
        currency: "AUD",
        category: "Top Up",
        status: "completed",
        description: "10:12",
        date: new Date("2025-07-18T10:12:00"),
        merchantIcon: "apple",
        iconColor: "#000000",
      },
      // Add some Sardinia transactions for variety
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-30.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "21:56 • -A$49.50",
        date: new Date("2025-07-19T21:56:00"),
        merchantIcon: "Z",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Zuma Porto Cervo",
        amount: "-28.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "22:26 • -A$46.20",
        date: new Date("2025-07-19T22:26:00"),
        merchantIcon: "Z",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Sardinia Boat Charter S.R.L.",
        amount: "-2400.00",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "13:09 • -A$3,960.00",
        date: new Date("2025-07-20T13:09:00"),
        merchantIcon: "S",
        iconColor: "#9333EA",
      },
      {
        userId: thomasId,
        merchant: "Novikov Porto Cervo",
        amount: "-380.00",
        currency: "AUD",
        category: "Food & Drink",
        status: "completed",
        description: "20:18 • -A$627.00",
        date: new Date("2025-07-20T20:18:00"),
        merchantIcon: "N",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Louis Vuitton Porto Cervo",
        amount: "-890.00",
        currency: "AUD",
        category: "Shopping",
        status: "completed",
        description: "17:05 • -A$1,468.50",
        date: new Date("2025-07-21T17:05:00"),
        merchantIcon: "LV",
        iconColor: "#DC2626",
      },
      {
        userId: thomasId,
        merchant: "Billionaire Club Porto Cervo",
        amount: "-120.00",
        currency: "AUD",
        category: "Entertainment",
        status: "completed",
        description: "23:00 • -A$198.00",
        date: new Date("2025-07-21T23:00:00"),
        merchantIcon: "B",
        iconColor: "#9333EA",
      },
      // Existing transactions continue below...
      {
        userId: thomasId,
        merchant: "GitHub",
        amount: "1.55",
        currency: "AUD",
        originalAmount: null,
        originalCurrency: null,
        category: "Technology",
        status: "reverted",
        description: "04:25 • Reverted",
        date: new Date("2024-08-17T04:25:00"),
        merchantIcon: "github",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Thomas Francis",
        amount: "-18.00",
        currency: "AUD",
        category: "Transfer",
        status: "completed",
        description: "18:06 • Sent from Revolut",
        date: new Date("2024-08-15T18:06:00"),
        merchantIcon: "TF",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "GitHub",
        amount: "15.46",
        currency: "AUD",
        category: "Technology",
        status: "reverted",
        description: "03:39 • Reverted",
        date: new Date("2024-08-15T03:39:00"),
        merchantIcon: "github",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "GitHub",
        amount: "-6.18",
        currency: "AUD",
        originalAmount: "-4.00",
        originalCurrency: "USD",
        category: "Technology",
        status: "completed",
        description: "03:35 • -US$4",
        date: new Date("2024-08-15T03:35:00"),
        merchantIcon: "github",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "GitHub",
        amount: "15.46",
        currency: "AUD",
        category: "Technology",
        status: "completed",
        description: "03:24 • Card verification",
        date: new Date("2024-08-15T03:24:00"),
        merchantIcon: "github",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "25.00",
        currency: "AUD",
        category: "Top Up",
        status: "completed",
        description: "03:23",
        date: new Date("2024-08-15T03:23:00"),
        merchantIcon: "apple",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "GitHub",
        amount: "15.46",
        currency: "AUD",
        category: "Technology",
        status: "failed",
        description: "02:04 • Insufficient balance",
        date: new Date("2024-08-15T02:04:00"),
        merchantIcon: "github",
        iconColor: "#000000",
      },
      // July transactions
      {
        userId: thomasId,
        merchant: "Rtf",
        amount: "-23.55",
        currency: "AUD",
        originalAmount: "-13.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "21:38 • -€13",
        date: new Date("2024-07-27T21:38:00"),
        merchantIcon: "R",
        iconColor: "#EC4899",
      },
      {
        userId: thomasId,
        merchant: "Pains De Provence",
        amount: "-2.18",
        currency: "AUD",
        originalAmount: "-1.20",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:28 • -€1.20",
        date: new Date("2024-07-27T20:28:00"),
        merchantIcon: "P",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Pains De Provence",
        amount: "-12.14",
        currency: "AUD",
        originalAmount: "-6.70",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "20:12 • -€6.70",
        date: new Date("2024-07-27T20:12:00"),
        merchantIcon: "P",
        iconColor: "#4ADE80",
      },
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "50.00",
        currency: "AUD",
        category: "Top Up",
        status: "completed",
        description: "19:48",
        date: new Date("2024-07-27T19:48:00"),
        merchantIcon: "apple",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Omio",
        amount: "-68.61",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "17:21",
        date: new Date("2024-07-27T17:21:00"),
        merchantIcon: "O",
        iconColor: "#FFFFFF",
      },
      {
        userId: thomasId,
        merchant: "Alimentation General",
        amount: "-3.63",
        currency: "AUD",
        originalAmount: "-2.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "11:35 • -€2",
        date: new Date("2024-07-27T11:35:00"),
        merchantIcon: "A",
        iconColor: "#6B7280",
      },
      {
        userId: thomasId,
        merchant: "McDonald's",
        amount: "-15.98",
        currency: "AUD",
        originalAmount: "-8.90",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "05:35 • -€8.90",
        date: new Date("2024-07-27T05:35:00"),
        merchantIcon: "M",
        iconColor: "#DA020E",
      },
      {
        userId: thomasId,
        merchant: "Lime",
        amount: "-11.29",
        currency: "AUD",
        originalAmount: "-6.29",
        originalCurrency: "EUR",
        category: "Transport",
        status: "completed",
        description: "05:07 • -€6.29",
        date: new Date("2024-07-27T05:07:00"),
        merchantIcon: "L",
        iconColor: "#65A30D",
      },
      {
        userId: thomasId,
        merchant: "Lime",
        amount: "0.00",
        currency: "AUD",
        category: "Transport",
        status: "completed",
        description: "05:07 • Card verification",
        date: new Date("2024-07-27T05:07:00"),
        merchantIcon: "L",
        iconColor: "#65A30D",
      },
      {
        userId: thomasId,
        merchant: "Jay",
        amount: "-8.97",
        currency: "AUD",
        originalAmount: "-5.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "04:14 • -€5",
        date: new Date("2024-07-27T04:14:00"),
        merchantIcon: "J",
        iconColor: "#FB923C",
      },
      // More July transactions
      {
        userId: thomasId,
        merchant: "Pharmacie du Voyage Roissy 1",
        amount: "-3.63",
        currency: "AUD",
        originalAmount: "-2.00",
        originalCurrency: "EUR",
        category: "Health",
        status: "completed",
        description: "23:38 • -€2",
        date: new Date("2024-07-26T23:38:00"),
        merchantIcon: "P",
        iconColor: "#FFFFFF",
      },
      {
        userId: thomasId,
        merchant: "Marché Franprix",
        amount: "-0.91",
        currency: "AUD",
        originalAmount: "-0.50",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "17:10 • -€0.50",
        date: new Date("2024-07-26T17:10:00"),
        merchantIcon: "M",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "Burger Foods",
        amount: "-10.88",
        currency: "AUD",
        originalAmount: "-6.00",
        originalCurrency: "EUR",
        category: "Food & Drink",
        status: "completed",
        description: "03:39 • -€6",
        date: new Date("2024-07-26T03:39:00"),
        merchantIcon: "B",
        iconColor: "#FB923C",
      },
      {
        userId: thomasId,
        merchant: "yesim",
        amount: "-12.69",
        currency: "AUD",
        originalAmount: "-7.00",
        originalCurrency: "EUR",
        category: "Technology",
        status: "completed",
        description: "00:32 • -€7",
        date: new Date("2024-07-26T00:32:00"),
        merchantIcon: "Y",
        iconColor: "#FFFFFF",
      },
      {
        userId: thomasId,
        merchant: "Olvadis",
        amount: "-1.82",
        currency: "AUD",
        originalAmount: "-1.00",
        originalCurrency: "EUR",
        category: "Shopping",
        status: "completed",
        description: "00:06 • -€1",
        date: new Date("2024-07-26T00:06:00"),
        merchantIcon: "O",
        iconColor: "#EC4899",
      },
      {
        userId: thomasId,
        merchant: "Money added via Apple Pay",
        amount: "25.00",
        currency: "AUD",
        category: "Top Up",
        status: "completed",
        description: "23:07",
        date: new Date("2024-07-25T23:07:00"),
        merchantIcon: "apple",
        iconColor: "#000000",
      },
      {
        userId: thomasId,
        merchant: "Thomas Francis",
        amount: "-5.00",
        currency: "AUD",
        category: "Transfer",
        status: "completed",
        description: "23:07 • Sent from Revolut",
        date: new Date("2024-07-25T23:07:00"),
        merchantIcon: "TF",
        iconColor: "#FB923C",
      },
    ];

    transactions.forEach(transaction => {
      const id = randomUUID();
      this.transactions.set(id, { ...transaction, id });
    });

    // Create crypto assets
    const cryptoAssets: CryptoAsset[] = [
      {
        id: "bitcoin",
        symbol: "BTC",
        name: "Bitcoin",
        price: "178792.00",
        change24h: "0.25",
        chartData: [
          { time: 1, value: 175000 },
          { time: 2, value: 176500 },
          { time: 3, value: 178000 },
          { time: 4, value: 179200 },
          { time: 5, value: 178792 }
        ],
        icon: "₿",
      },
      {
        id: "ethereum",
        symbol: "ETH",
        name: "Ethereum",
        price: "6635.63",
        change24h: "-0.71",
        chartData: [
          { time: 1, value: 6800 },
          { time: 2, value: 6750 },
          { time: 3, value: 6700 },
          { time: 4, value: 6650 },
          { time: 5, value: 6635.63 }
        ],
        icon: "Ξ",
      },
      {
        id: "0x",
        symbol: "XCN",
        name: "0x Protocol",
        price: "0.45",
        change24h: "23.44",
        icon: "0x",
      },
      {
        id: "polygon",
        symbol: "MATIC",
        name: "Polygon",
        price: "1.23",
        change24h: "4.14",
        icon: "⬟",
      },
      {
        id: "polkadot",
        symbol: "POL",
        name: "Polkadot",
        price: "8.92",
        change24h: "4.10",
        icon: "●",
      },
      {
        id: "golem",
        symbol: "GLM",
        name: "Golem",
        price: "0.34",
        change24h: "3.40",
        icon: "G",
      },
      {
        id: "amp",
        symbol: "AMP",
        name: "Amp",
        price: "0.012",
        change24h: "3.19",
        icon: "A",
      },
      {
        id: "qtum",
        symbol: "QI",
        name: "Qtum",
        price: "4.56",
        change24h: "2.64",
        icon: "Q",
      },
      {
        id: "cronos",
        symbol: "CRO",
        name: "Cronos",
        price: "0.18",
        change24h: "2.39",
        icon: "C",
      },
      {
        id: "loot",
        symbol: "AGLD",
        name: "Adventure Gold",
        price: "2.34",
        change24h: "2.36",
        icon: "L",
      },
    ];

    cryptoAssets.forEach(asset => {
      this.cryptoAssets.set(asset.id, asset);
    });
  }

  async getUser(id: string): Promise<User | undefined> {
    return this.users.get(id);
  }

  async getUserByUsername(username: string): Promise<User | undefined> {
    return Array.from(this.users.values()).find(
      (user) => user.username === username,
    );
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    const id = randomUUID();
    const user: User = { ...insertUser, id, createdAt: new Date() };
    this.users.set(id, user);
    return user;
  }

  async getUserTransactions(userId: string): Promise<Transaction[]> {
    return Array.from(this.transactions.values())
      .filter(transaction => transaction.userId === userId)
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }

  async createTransaction(insertTransaction: InsertTransaction): Promise<Transaction> {
    const id = randomUUID();
    const transaction: Transaction = { ...insertTransaction, id, date: new Date() };
    this.transactions.set(id, transaction);
    return transaction;
  }

  async getUserCards(userId: string): Promise<Card[]> {
    return Array.from(this.cards.values())
      .filter(card => card.userId === userId);
  }

  async createCard(insertCard: InsertCard): Promise<Card> {
    const id = randomUUID();
    const card: Card = { ...insertCard, id, createdAt: new Date() };
    this.cards.set(id, card);
    return card;
  }

  async getCryptoAssets(): Promise<CryptoAsset[]> {
    return Array.from(this.cryptoAssets.values());
  }

  async updateCryptoAsset(asset: CryptoAsset): Promise<CryptoAsset> {
    this.cryptoAssets.set(asset.id, asset);
    return asset;
  }
}

export const storage = new MemStorage();
